MAGECLOUD-1332: Add ability to configure cron_consumers_runner via an environment variable
magento/ece-tools pull request #102
Opened 2017-11-28 12:20 UTC by BaDos

### Description
Magento allows to configure cron_consummers_runner via app/etc/env.php
We added opportunity to configure cron job cron_consummers_runner via an environment variable CRON_CONSUMERS_RUNNER.

### Fixed Issues (if relevant)
https://magento2.atlassian.net/browse/MAGECLOUD-1332

### Zephyr Tests
https://jira.corp.magento.com/browse/MAGETWO-84602

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] Pull request was approved by architect
 - [ ] Pull request was approved by QA member
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-11-28 13:22 UTC, shiftedreality approved these changes

2017-11-28 13:50 UTC, NadiyaS approved these changes
lack of descriptions especially for CronConsummerRunner

2017-11-28 14:03 UTC, NadiyaS requested changes

2017-11-28 14:19 UTC, NadiyaS approved these changes
approved. Descriptions should be added later

2017-11-29 14:07 UTC, andriyShevtsov approved these changes

2017-11-29 14:09 UTC, merged