MAGECLOUD-1444: Refactor Flag Files
magento/ece-tools pull request #123
Opened 2017-12-18 14:59 UTC by oshmyheliuk

### Description

### Fixed Issues (if relevant)

https://magento2.atlassian.net/browse/MAGECLOUD-1444

### Zephyr Tests

1. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] Pull request was approved by architect
 - [ ] Pull request was approved by QA member
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-12-18 16:02 UTC, shiftedreality requested changes

2017-12-26 13:16 UTC, shiftedreality requested changes

2018-01-03 11:43 UTC, NadiyaS requested changes
pay attention to methods where you call FlagManager methods

2018-01-04 11:14 UTC, shiftedreality approved these changes

2018-01-04 11:17 UTC, NadiyaS approved these changes

2018-01-04 12:33 UTC, merged