MAGECLOUD-1514: Verify SCD strategies support
magento/ece-tools pull request #157
Opened 2018-01-23 17:18 UTC by michaelcasey316

Choose the SCD strategy depending on the Magento version.

### Description

This pull request changes the static content deployment strategy getter. Instead of simply returning a defined value, it checks another set of methods to determine what the appropriate SCD strategy is. These methods internally generate a list of allowed SCD strategies, choose the desired strategy if possible, and fall back to the highest priority in the allowed list if not. The user can override both the allowed SCD strategy list and the desired SCD strategy with "stage config". 

These changes are necessary to allow ece-tools to work with multiple versions of Magento, each with differing SCD strategies.

### Fixed Issues (if relevant)

1. ece-tools can now handle when different versions of Magento have different static content deployment strategies.
2. ece-tools no longer attempts to add a "-s" switch to the SCD command line when Magento is below version 2.2.

### Zephyr Tests

1. https://jira.corp.magento.com/browse/MAGETWO-87168
2. https://jira.corp.magento.com/browse/MAGETWO-87249

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] Pull request was approved by architect
 - [x] Pull request was approved by QA member
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-01-23 18:24 UTC, billygilbert requested changes

2018-01-23 22:29 UTC, JacobBrownAustin requested changes

2018-01-24 20:49 UTC, JacobBrownAustin approved these changes
I approve this.

2018-01-24 21:34 UTC, billygilbert requested changes

2018-01-24 21:43 UTC, billygilbert approved these changes

2018-01-25 17:41 UTC, merged