MAGECLOUD-1513: Ensure 2.1.x Environment Variables Support
magento/ece-tools pull request #169
Opened 2018-01-29 13:55 UTC by shiftedreality

2.1.x Cloud environment variables should be supported on ece-tools. In this task we need a list of all known environment variables used in 2.1.x/mcc. Where the variable has been redefined ece-tools should be re-factored to handle either variable name.

### Description

### Fixed Issues (if relevant)

1. Adds `GENERATED_CODE_SYMLINKS` variable

### Zephyr Tests

1. https://jira.corp.magento.com/browse/MAGETWO-67598

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] Pull request was approved by architect
 - [ ] Pull request was approved by QA member
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-01-29 16:12 UTC, bbatsche requested changes

2018-01-29 16:13 UTC, billygilbert approved these changes

2018-01-30 16:31 UTC, bbatsche approved these changes

2018-01-30 20:16 UTC, JacobBrownAustin requested changes
Was VAR_GENERATED_CODE_SYMLINK the only variable missing for 2.1 support?

2018-02-01 09:26 UTC, oshmyheliuk approved these changes

2018-02-01 15:22 UTC, JacobBrownAustin approved these changes

2018-02-01 16:35 UTC, merged