MAGECLOUD-1282: Disable Solr configuration on Magento >= 2.2
magento/ece-tools pull request #187
Opened 2018-02-08 15:38 UTC by bbatsche

### Description

Skip past checking for Solr config when Magento version is 2.2 or greater.

### Fixed Issues (if relevant)

[MAGECLOUD-1282](https://magento2.atlassian.net/browse/MAGECLOUD-1282)

### Zephyr Tests

[MAGETWO-90012](https://jira.corp.magento.com/browse/MAGETWO-90012)

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] Pull request was approved by architect
 - [ ] Pull request was approved by QA member
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-02-12 21:29 UTC, billygilbert requested changes
This is kind of unrelated to the PR but it seems to me we need to go back and update MAGECLOUD-1282 with respects to the new requirements (disabling at 2.1 vs. 2.2).  After that we should update the title of the PR to actually reflect the changes as they don't currently.

@YPyltiai Do you own this or should @bbatsche make this change?

2018-02-28 16:36 UTC, JacobBrownAustin approved these changes

2018-02-28 16:41 UTC, billygilbert approved these changes
Approved pending response from Docs.  Need to see if we need to add a message noting that we are falling back to MySQL for 2.2 when Solr is configured.

2018-02-28 16:57 UTC, michaelcasey316 approved these changes

2018-02-28 17:26 UTC, shiftedreality approved these changes

2018-02-28 17:44 UTC, billygilbert requested changes
Approved after doing the things Heather said :D

2018-04-04 15:10 UTC, merged