MAGECLOUD-1819: VERBOSE_COMMANDS Stops Deployment if Value is Incorrect
magento/ece-tools pull request #204
Opened 2018-03-08 21:20 UTC by shiftedreality

https://magento2.atlassian.net/browse/MAGECLOUD-1819

### Description

### Fixed Issues (if relevant)

1. Added validation of `.magento.env.yaml` to build phase
2. Added validation of enviroenmnt values to deploy phase

### Zephyr Tests

1. https://jira.corp.magento.com/browse/MAGETWO-89117

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] Pull request was approved by architect
 - [ ] Pull request was approved by QA member
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-03-08 22:36 UTC, billygilbert requested changes

2018-03-09 14:19 UTC, JacobBrownAustin requested changes
We need it for both build and deploy, not just one or the other.  
The reason we need it for build is because we want to check early and fail first in build, so that if there is problem, build gets aborted, and website stays live on previous code.
The reason we need it for deploy phase as well is because if the user modifies their VERBOSE_COMMANDS variable with the platform.sh environment variable, it will trigger a deploy only (no build first).

2018-03-12 21:35 UTC, billygilbert requested changes

2018-03-13 15:38 UTC, billygilbert approved these changes
Architect approved.

2018-03-13 15:41 UTC, JacobBrownAustin approved these changes

2018-03-21 16:33 UTC, merged