MAGECLOUD-1963: Add SCD on demand and SCD on build wizards
magento/ece-tools pull request #230
Opened 2018-04-06 18:11 UTC by shiftedreality

https://magento2.atlassian.net/browse/MAGECLOUD-1963

### Description

Added 2 new commands to verify the current configuration:
- `./bin/vendor/ece-tools wizard:scd-on-build` - Verifies config for SCD on build
- `./bin/vendor/ece-tools wizard:scd-on-deploy` - Verifies config for SCD on deploy
- `./bin/vendor/ece-tools wizard:scd-on-demand` - Verifies config for SCD on demand

### Zephyr Tests

1. https://jira.corp.magento.com/browse/MAGETWO-90195
2. https://jira.corp.magento.com/browse/MAGETWO-90196
3. https://jira.corp.magento.com/browse/MAGETWO-90459

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] Pull request was approved by architect
 - [ ] Pull request was approved by QA member
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-04-11 14:58 UTC, bbatsche requested changes
Mostly questions, but a couple of items that should be changed.

2018-04-11 18:19 UTC, billygilbert requested changes
The only thing I think really needs to change is the one I agreed with Ben on re: log levels.  If we feel it's overkill to test for both phases as well as global I'm ok with that.

2018-04-11 22:14 UTC, michaelcasey316 requested changes

2018-04-12 19:19 UTC, bbatsche approved these changes

2018-04-12 20:58 UTC, billygilbert approved these changes

2018-04-13 16:41 UTC, merged