MAGECLOUD-1501: Deploy Specific Locales per Theme
magento/ece-tools pull request #235
Opened 2018-04-17 20:47 UTC by shiftedreality

https://magento2.atlassian.net/browse/MAGECLOUD-1501

### Description

This PR adds the possibility to configure matrix of deployed themes.

- [Design document](https://wiki.corp.magento.com/display/SUSENG/ECE-Tools%3A+Deploy+Specific+Locales+per+Theme)

### Zephyr Tests

1. https://jira.corp.magento.com/browse/MAGETWO-72271
2. https://jira.corp.magento.com/browse/MAGETWO-89740
3. https://jira.corp.magento.com/browse/MAGETWO-72296
4. https://jira.corp.magento.com/browse/MAGETWO-90874

2018-04-26 15:23 UTC, bbatsche requested changes

2018-04-26 20:09 UTC, JacobBrownAustin requested changes
just variable name change and requesting comments for deprecated methods.

2018-04-26 20:54 UTC, JacobBrownAustin approved these changes
thank you

2018-04-27 16:36 UTC, bbatsche requested changes

2018-04-27 17:13 UTC, billygilbert requested changes

2018-04-27 18:51 UTC, bbatsche approved these changes

2018-04-27 19:03 UTC, billygilbert approved these changes

2018-04-30 20:54 UTC, merged