MAGECLOUD-1506: Possibility to Disable Clean Static Files on Build Phase
magento/ece-tools pull request #259
Opened 2018-05-16 21:20 UTC by billygilbert

### Description
Adding ability to disable cleaning of static files if SCD is done on build phase.  Option is tied to the deploy phase as that is where the action of copying actually takes place. 

### Zephyr Tests
1. https://jira.corp.magento.com/browse/MAGETWO-91582

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] Pull request was approved by architect
 - [ ] Pull request was approved by QA member
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-06-14 13:23 UTC, mmansoor-magento commented
[![CLA assistant check](https://cla.dev.magento.com/pull/badge/signed)](https://cla.dev.magento.com/magento/magento2) <br/>All committers have signed the CLA.

2018-06-21 17:56 UTC, shiftedreality approved these changes

2018-06-21 18:10 UTC, bbatsche requested changes
Only things that actually need to change is the type hints on two methods. Other comments are just questions or observations

2018-06-21 18:38 UTC, bbatsche approved these changes

2018-06-22 16:11 UTC, merged