MAGECLOUD-2227: Cleanup Build & Deploy Log Output
magento/ece-tools pull request #274
Opened 2018-06-01 18:53 UTC by bbatsche

### Description

Changes some of the log levels around building & deploying Magento, so that developers can have more fine grained control over what log messages they want displayed.

### Fixed Issues (if relevant)

[MAGECLOUD-2227](https://magento2.atlassian.net/browse/MAGECLOUD-2227)

### Zephyr Tests

No behavior was significantly changed, a basic smoke test should be sufficient.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] Pull request was approved by architect
 - [ ] Pull request was approved by QA member
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-06-04 19:47 UTC, shiftedreality requested changes

2018-06-25 13:56 UTC, JacobBrownAustin approved these changes

2018-07-03 20:38 UTC, billygilbert reviewed
Looks good, only thing that was off is looked like documentation update was missed in one spot.

2018-07-06 17:40 UTC, billygilbert approved these changes

2018-07-06 18:29 UTC, shiftedreality approved these changes

2018-07-06 18:30 UTC, merged