Magecloud 2182: Fixing background file directory deleting
magento/ece-tools pull request #287
Opened 2018-06-22 19:06 UTC by JacobBrownAustin

https://magento2.atlassian.net/browse/MAGECLOUD-2182
### Description

Because we were deleting directories in a background process without any management of those processes, we had a few issues.  This pull request fixes those issues.

### Fixed Issues (if relevant)

1. ~~`ece-tools deploy` now waits on child processes before it finishes.  Now we no longer have undefined behaviour by having child processes continue after deployment is complete.~~  I was asked to move this to a separate task/pull request.
2. We no longer attempt to compress files in the directories that are getting deleted in the background.
3. Fixed some shell escape bugs.
4. No longer hard-coding the 'pub/static path' in StaticContentCompress.php

### Manual testing scenarios

1.  https://jira.corp.magento.com/browse/MAGETWO-93000

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-06-25 16:23 UTC, billygilbert requested changes

2018-06-25 21:28 UTC, shiftedreality requested changes

2018-06-26 01:16 UTC, shiftedreality approved these changes

2018-06-26 15:33 UTC, billygilbert approved these changes
Through a comment in there, not really necessary though.

2018-06-26 19:26 UTC, merged