MAGECLOUD-2372: Run ideal-state smart wizard during each build
magento/ece-tools pull request #329
Opened 2018-08-07 18:14 UTC by bbatsche

### Description

1. Move ideal-state's logic to a composite validator
1. Add ideal-state validator to build process
1. Use child validators' error in ideal-state, rather than generating redundant/duplicate errors, so we can centralize language changes
1. Update & clarify instructions for performing SCD on build.

### Fixed Issues (if relevant)

[MAGECLOUD-2372](https://magento2.atlassian.net/browse/MAGECLOUD-2372)

### Manual testing scenarios

[MAGETWO-94063](https://jira.corp.magento.com/browse/MAGETWO-94063)

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-08-09 13:31 UTC, shiftedreality requested changes

2018-08-09 13:48 UTC, hguthrie reviewed
These suggestions also pertain to the other sets of error messages.

2018-08-23 14:20 UTC, shiftedreality approved these changes

2018-08-23 15:04 UTC, billygilbert requested changes

2018-08-23 16:25 UTC, billygilbert approved these changes

2018-08-23 18:04 UTC, merged