MAGECLOUD-2600: ElasticSearch Version Validation - Required Improvements
magento/ece-tools pull request #336
Opened 2018-08-13 07:18 UTC by oshmyheliuk

### Description
Replace error message to clearly describe the issue and suggest ways of fixing it:
Specify clearly which version is used where (infra / app)
Specify options to fix:

- If you want to use ES v5.x in application - upgrade your version on infra layer
- If you want to use ES v1.x / v2.x on infrastructure, update your ES version in app to elasticsearch/elasticsearch ~2.0

If ElasticSearch is not used (for example, MySQL is used instead), downgrade level of error to Notice / Warning, suggesting to remove ES from infrastructure level, if it is not expected to be used going forward.

### Fixed Issues (if relevant)
https://magento2.atlassian.net/browse/MAGECLOUD-2600

### Manual testing scenarios

https://jira.corp.magento.com/browse/MAGETWO-94127
https://jira.corp.magento.com/browse/MAGETWO-93304

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-08-13 13:47 UTC, NadiyaS approved these changes

2018-08-16 13:39 UTC, meker12 requested changes
I noticed some issues in the user messages that could be improved.

2018-08-16 18:42 UTC, meker12 approved these changes

2018-08-17 11:00 UTC, arhiopterecs approved these changes

2018-08-17 11:10 UTC, merged