Magecloud 2904
magento/ece-tools pull request #399
Opened 2018-12-17 22:52 UTC by billygilbert

### Description

### Fixed Issues (if relevant)

1. magento/ece-tools#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2018-12-18 16:32 UTC, bbatsche commented on src/StaticContent/ThemeResolver.php
> +    public function getThemeName(string $themePath): string
Man I don't like this method, but I don't have a good answer for what the alternative should be

2019-01-02 21:26 UTC, shiftedreality commented on src/Filesystem/Driver/File.php
> +    public function glob(string $path): array
It's better to pass `NO_SORT` option by default, this will improve performance

2019-01-03 18:02 UTC, shiftedreality commented on src/StaticContent/ThemeResolver.php
> +        try {
I see you already adding coupling on Magento. So maybe it's better to retrieve them from `\Magento\Framework\Component\ComponentRegistrar:$paths`?

I see it's private but we can use reflection easily:

```
if (class_exists(\Magento\Framework\Component\ComponentRegistrar::class)) {
    $reflectionClass = new \ReflectionClass(\Magento\Framework\Component\ComponentRegistrar::class);
    $property = $reflectionClass->getProperty('paths');
    $property->setAccessible(true);

    $paths = $property->getValue($reflectionClass)['theme'];

    die(var_dump(array_keys($paths)));
}
```

2019-01-08 17:27 UTC, shiftedreality requested changes

2019-01-08 17:27 UTC, shiftedreality commented on src/Filesystem/DirectoryList.php
> +    const DIR_DESIGN = 'design';
It seems like we can remove both of these constants

2019-01-08 17:27 UTC, shiftedreality commented on src/StaticContent/ThemeResolver.php
> +        return '';
Can we have a fallback when no theme foud and use provided value? Otherwise, it will break local setup having ece-tools dependent on Magento

2019-01-09 16:11 UTC, shiftedreality approved these changes

2019-01-09 20:32 UTC, andriyShevtsov commented
QA  approved

2019-01-10 16:58 UTC, merged