MAGECLOUD-3048: Allow setting of x-frame options within configuration…
magento/ece-tools pull request #407
Opened 2019-01-11 21:23 UTC by shiftedreality

… file

### Description

### Fixed Issues (if relevant)

1. https://magento2.atlassian.net/browse/MAGECLOUD-3048

### Manual testing scenarios

1. https://jira.corp.magento.com/browse/MAGETWO-97626

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-01-11 21:26 UTC, billygilbert requested changes
Also needs an update to dist/.magento.env.yaml

2019-01-11 21:26 UTC, billygilbert commented on src/Config/Schema.php
> +                    StageConfigInterface::STAGE_GLOBAL => ''
looks like default should be SAMEORIGIN.  That's what I get in my env.php without changing anything.

2019-01-11 21:30 UTC, shiftedreality commented on src/Config/Schema.php
> +                    StageConfigInterface::STAGE_GLOBAL => ''
This will be backward incompatible because will overwrite custom values.

2019-01-14 14:05 UTC, YPyltiai commented
@shiftedreality / @billygilbert - would it be better to move it into `system` section? Doesn't logically fit into `global` (no effect on deployment process).  It's not a requirement - just a question.

2019-01-14 15:21 UTC, shiftedreality commented
@billygilbert fix both comments, changing this value by default seems not very risky.
@YPyltiai it's on the same level as cache settings for example

2019-01-14 15:24 UTC, YPyltiai commented
Then it's fine.

2019-01-14 15:38 UTC, billygilbert commented
Maybe at some point it makes sense to move these all to an `SYSTEM>ENV` section...or something that denotes it specifically affects env.php but I agree with @shiftedreality for now.  Approved.

2019-01-14 15:38 UTC, billygilbert approved these changes

2019-01-14 20:36 UTC, mveeramneni commented
QA Approved

2019-01-14 20:44 UTC, merged