MAGECLOUD-2882: Duplication beetwen SCD_EXCLUDE_THEME and SCD_MATRIX
magento/ece-tools pull request #412
Opened 2019-01-22 22:25 UTC by oshmyheliuk

### Description
Added deprecation for the SCD_EXCLUDE_THEME variable. This variable became redundant after adding SCD_MATRIX.

### Fixed Issues (if relevant)

https://magento2.atlassian.net/browse/MAGECLOUD-2882

### Manual testing scenarios

https://jira.corp.magento.com/browse/MAGETWO-97873

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-01-24 19:57 UTC, shiftedreality commented on src/Config/Validator/Build/StageConfigDeprecatedVariables.php
> +                'error' => 'Some configuration in your .magento.env.yaml file is deprecated.',
Shouldn't this be in plural?

2019-01-24 19:58 UTC, shiftedreality approved these changes

2019-01-24 19:58 UTC, shiftedreality commented on src/Config/StageConfigInterface.php
> +     * @deprecated use SCD_MATRIX instead
Add dot in the end

2019-01-24 20:58 UTC, oshmyheliuk commented on src/Config/Validator/Build/StageConfigDeprecatedVariables.php
> +                'error' => 'Some configuration in your .magento.env.yaml file is deprecated.',
changed

2019-01-24 20:58 UTC, oshmyheliuk commented on src/Config/StageConfigInterface.php
> +     * @deprecated use SCD_MATRIX instead
added

2019-01-24 21:17 UTC, BaDos requested changes
Please add information about deprecated variable into the `.magento.env.yaml.dist` file

2019-01-24 21:42 UTC, oshmyheliuk commented
@BaDos Information added

2019-01-24 21:43 UTC, BaDos approved these changes

2019-01-25 15:48 UTC, andriyShevtsov commented
QA approved

2019-01-28 15:49 UTC, merged