MAGECLOUD-2899: Redis Slave Nodes Have no Health Checks / Are not Stable
magento/ece-tools pull request #435
Opened 2019-03-27 17:43 UTC by arhiopterecs

MAGECLOUD-2899: Redis Slave Nodes Have no Health Checks / Are not Stable

### Description
In a case when using Redis slave, adds a couple of items to the cache settings in file `app/etc/env.php`. 
A feature of this configuration is that in case of failure Redis Slave, Magento should use master for reading.

### Fixed Issues (if relevant)
1. magento/ece-tools#MAGECLOUD-2899: Redis Slave Nodes Have no Health Checks / Are not Stable

### Manual testing scenarios

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-04-03 17:14 UTC, michaelcasey316 requested changes
According to Balázs Galántai, the integrity of the replica must be verified before using it in place of the primary (https://magento2.atlassian.net/browse/MAGECLOUD-2899?focusedCommentId=61967&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-61967). The example they gave involved the following commands:

`SENTINEL masters - Show a list of monitored masters and their state.`
`SENTINEL master <master name> -  Show the state and info of the specified master.`
`SENTINEL slaves <master name> - Show a list of slaves for this master, and their state.` 

Did you determine that integrity verification is unnecessary?

2019-04-03 21:11 UTC, kandy commented
@michaelcasey316 Currently we do not need this functionality, because primary reason to use local instances is lower latency due to avoiding interaction over a network, and we verify that when slave fails we switch to master

2019-04-03 21:34 UTC, michaelcasey316 commented
@kandy Not checking the state of the cluster before using the replica breaks strong consistency, doesn't it? Even if Magento is designed to never need up to date information in Redis, what about third party extensions that assume Redis doesn't have outdated data?

2019-04-03 21:39 UTC, kandy commented
@michaelcasey316 Redis is not transaction storage and I don't think that is good  to expect consistency from it

2019-04-04 16:31 UTC, michaelcasey316 approved these changes

2019-04-08 17:53 UTC, mveeramneni commented
QA Approved

2019-04-12 15:16 UTC, YPyltiai commented on patches.json
> +  "colinmollenhour/cache-backend-redis": {
Please re-define constraints to map to Magento Core versions.

2019-04-15 21:27 UTC, bbatsche approved these changes

2019-04-16 18:36 UTC, oshmyheliuk approved these changes

2019-04-17 19:37 UTC, mveeramneni commented
QA Approved

2019-04-17 20:07 UTC, merged