MAGECLOUD-3382: Increase default SCD_THREADS to 3
magento/ece-tools pull request #447
Opened 2019-04-18 20:31 UTC by oshmyheliuk

### Description
Default value of SCD_THREADS is set to 4 if enough CPU threads.

### Fixed Issues (if relevant)

https://magento2.atlassian.net/browse/MAGECLOUD-3382

### Manual testing scenarios

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-04-18 21:23 UTC, shiftedreality requested changes

2019-04-18 21:23 UTC, shiftedreality commented on src/App/Container.php
> +                        $this->container->make(DeployProcess\PreDeploy\SetProductionMode::class),
Let's move it upper to `Process` namespace

2019-04-18 21:23 UTC, shiftedreality commented on src/Test/Unit/Config/SchemaTest.php
> +                BuildInterface::VAR_SCD_THREADS => -1,
Nice ❤️

2019-04-18 21:23 UTC, shiftedreality commented on src/Test/Unit/Util/CpuTest.php
> +    private $cpu;
Target class better to keep in top of properties, those won't move with adding/deleting them later

2019-04-18 21:26 UTC, oshmyheliuk commented on src/App/Container.php
> +                        $this->container->make(DeployProcess\PreDeploy\SetProductionMode::class),
I thought about creation `Process\Common` folder to put there all processes that can be on all stages. What do you think?

2019-04-18 21:27 UTC, shiftedreality commented on src/App/Container.php
> +                        $this->container->make(DeployProcess\PreDeploy\SetProductionMode::class),
That's would be over-complication, I would keep in `Process` as parent

2019-04-19 20:02 UTC, shiftedreality approved these changes

2019-04-19 20:11 UTC, michaelcasey316 approved these changes

2019-04-22 19:32 UTC, mveeramneni commented
QA Approved

2019-04-22 19:34 UTC, merged