MAGECLOUD-3510: Fix an Issue with db-dump Command Related to DEFINERS
magento/ece-tools pull request #482
Opened 2019-05-03 13:12 UTC by oshmyheliuk

### Description
Add functionality for removing definers during ece-tool `db-dump` command.
Added option `--keep-definers` to preserve definers in the dumped file.

### Fixed Issues (if relevant)

https://magento2.atlassian.net/browse/MAGECLOUD-3510

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-05-03 18:19 UTC, bbatsche submitted a review, later dismissed

2019-05-06 15:00 UTC, shiftedreality requested changes

2019-05-06 15:00 UTC, shiftedreality commented on src/DB/DumpGenerator.php
> +    public function create(bool $keepDefiners = false)
Let's not use optional values as it adds complexity

2019-05-06 15:00 UTC, shiftedreality commented on src/Command/DbDump.php
> +            InputOption::VALUE_NONE,
Let's use `false` as default value

2019-05-06 15:25 UTC, oshmyheliuk commented on src/Command/DbDump.php
> +            InputOption::VALUE_NONE,
For `InputOption::VALUE_NONE` false is the default state, don't see a point to add this.

2019-05-06 15:26 UTC, oshmyheliuk commented on src/DB/DumpGenerator.php
> +    public function create(bool $keepDefiners = false)
Please give your suggestion on how to avoid it in this particular case

2019-05-06 15:52 UTC, oshmyheliuk commented on src/DB/DumpGenerator.php
> +    public function create(bool $keepDefiners = false)
done

2019-05-06 17:41 UTC, shiftedreality submitted a review, later dismissed

2019-05-08 19:17 UTC, arhiopterecs submitted a review, later dismissed

2019-05-20 19:20 UTC, shiftedreality approved these changes

2019-05-21 16:06 UTC, arhiopterecs approved these changes

2019-05-21 18:49 UTC, andriyShevtsov commented
QA approved

2019-05-22 13:48 UTC, merged