MAGECLOUD-3679: Add test to Cover BugFix from MAGECLOUD-3668
magento/ece-tools pull request #539
Opened 2019-06-10 15:46 UTC by BaDos

### Description

### Fixed Issues (if relevant)

https://magento2.atlassian.net/browse/MAGECLOUD-3679

### Manual testing scenarios

Need to perform a smoke testing `docker:build --mode=production` and `docker:build --mode=developer` and Docker as well

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-06-10 18:14 UTC, shiftedreality requested changes

2019-06-10 18:14 UTC, shiftedreality commented on src/Docker/Compose/ProductionCompose.php
> +    protected function getMagentoBuildVolumes(bool $isReadOnly): array
You should add `init` as well

2019-06-10 18:14 UTC, shiftedreality commented on tests/functional/Robo/Tasks/GenerateDockerCompose.php
> +    private $availableServices = ['php', 'nginx', 'db', 'es', 'redis', 'rmq', 'node'];
Use constants from `Service`

2019-06-12 16:01 UTC, BaDos commented on tests/functional/Robo/Tasks/GenerateDockerCompose.php
> +    private $availableServices = ['php', 'nginx', 'db', 'es', 'redis', 'rmq', 'node'];
Done

2019-06-12 16:01 UTC, BaDos commented on src/Docker/Compose/ProductionCompose.php
> +    protected function getMagentoBuildVolumes(bool $isReadOnly): array
It does not make sense.

2019-06-12 17:41 UTC, shiftedreality commented on src/Docker/Compose/ProductionCompose.php
> +    protected function getMagentoBuildVolumes(bool $isReadOnly): array
got it

2019-06-12 17:45 UTC, shiftedreality submitted a review, later dismissed

2019-06-12 18:42 UTC, billygilbert submitted a review, later dismissed

2019-06-13 17:19 UTC, andriyShevtsov commented
QA approved

2019-06-13 17:23 UTC, shiftedreality approved these changes

2019-06-13 18:33 UTC, billygilbert approved these changes

2019-06-13 18:34 UTC, merged

2019-06-13 18:34 UTC, ghost commented
Hi @BaDos, thank you for your contribution! </br>Please, complete [Contribution Survey](https://opensource.magento.com/survey/contribution/magento+ece-tools+539), it will take less than a minute. </br>Your feedback will help us to improve contribution process.