MAGECLOUD-1089 Automatically handle missing config.php and freshly in…
magento/ece-tools pull request #55
Opened 2017-10-11 16:33 UTC by ngeron

…stalled modules

### Description

https://magento2.atlassian.net/browse/MAGECLOUD-1089

Adds support for handling missing or out of data module configuration.

### Fixed Issues (if relevant)

1. Missing config.php or module section is handled during build
2. Modules installed but not enabled are enabled unless explicitly disabled in config

### Manual testing scenarios

1. https://jira.corp.magento.com/browse/MAGETWO-81656
2. https://jira.corp.magento.com/browse/MAGETWO-81658

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [ ] Pull request was approved by architect
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

2017-10-18 12:15 UTC, shiftedreality requested changes

2017-10-24 15:31 UTC, shiftedreality approved these changes

2017-10-24 21:32 UTC, michaelcasey316 approved these changes

2017-10-24 21:37 UTC, billygilbert approved these changes
Ran through the Zephyr tests, both passed and did some additional negative testing.

2017-10-25 07:37 UTC, kandy approved these changes

2017-10-25 07:38 UTC, merged