MAGECLOUD-1069: Static content compression
magento/ece-tools pull request #58
Opened 2017-10-18 16:12 UTC by michaelcasey316

### Description
This pull request adds static content compression to ece-tools. Previously, this was done with a shell command in the Platform.sh configuration. 
 
Compression is automatically activated after static content deployment is complete. This works when static content deployment runs in either the build or deploy phases. Nothing is compressed if static content deployment doesn't happen.

Ahead-of-time static content compression requires minimal space: only about 30% of the uncompressed size of the assets being compressed. It reduces web server CPU load as content compression doesn't need to be repeated for every request. It reduces disk I/O since compressed files are smaller when read from disk. The reduced CPU usage and disk I/O speeds page loads directly and allows for more simultaneous users indirectly.
 
### Fixed Issues (if relevant)
- https://magento2.atlassian.net/browse/MAGECLOUD-1069
 
### Manual testing scenarios
- https://jira.corp.magento.com/browse/MAGETWO-82442
- https://jira.corp.magento.com/browse/MAGETWO-82443
 
### Contribution checklist
- [x] Pull request has a meaningful description of its purpose
- [x] Pull request was approved by architect
- [x] All commits are accompanied by meaningful commit messages
- [x] All new or changed code is covered with unit/integration tests (if applicable)
- [x] All automated tests passed successfully (all builds on Travis CI are green)

2017-10-18 21:21 UTC, JacobBrownAustin approved these changes

2017-10-23 08:55 UTC, shiftedreality requested changes

2017-10-24 13:21 UTC, shiftedreality requested changes

2017-10-25 07:44 UTC, shiftedreality approved these changes

2017-10-25 12:27 UTC, kandy approved these changes

2017-10-25 20:22 UTC, billygilbert approved these changes
Approved pending the changes to the test cases.

2017-10-26 05:54 UTC, merged