MAGECLOUD-4128:  Release ECE-Tools 2002.0.21
magento/ece-tools pull request #592
Opened 2019-08-20 20:53 UTC by oshmyheliuk

### Description
Bumping version

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-08-20 20:56 UTC, billygilbert approved these changes

2019-08-20 20:59 UTC, shiftedreality approved these changes

2019-08-21 02:28 UTC, shiftedreality requested changes

2019-08-21 02:28 UTC, shiftedreality commented on composer.json
> +  "version": "2002.0.21",
It must go into 2002.0

2019-08-21 13:31 UTC, oshmyheliuk commented on composer.json
> +  "version": "2002.0.21",
Fixed

2019-08-21 17:28 UTC, shiftedreality approved these changes

2019-08-21 17:30 UTC, merged