MAGECLOUD-4071: Re-work consumers to terminate as soon as there is nothing left to process
magento/ece-tools pull request #594
Opened 2019-08-23 18:33 UTC by BaDos

### Description

Extend the CronKill process, add consumer killing

Add new configuration **CONSUMERS_WAIT_MAX_MESSAGES** to configure consumers behavior, default value on the Cloud is 0
If this value is 1, then a consumer waits for a message to process it, until processes max-messages from a queue.
If this value is 0, then a consumer processes available  messages from a queue and dies, even if a number of messages less than max-messages

### Fixed Issues (if relevant)

https://magento2.atlassian.net/browse/MAGECLOUD-4071

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-08-26 15:56 UTC, shiftedreality submitted a review, later dismissed

2019-08-26 15:56 UTC, shiftedreality commented on dist/.magento.env.yaml
> +# CONSUMERS_WAIT_MAX_MESSAGES - use this variable to configure consumers behavior.                                    #
@meker12 is it ok? Concerned about using `FOR` `CONSUMERS_WAIT_FOR_MAX_MESSAGES`

2019-08-26 20:19 UTC, billygilbert submitted a review, later dismissed
Approved but adding Margaret to review .magento.env.yaml.dist as that needs a review.

2019-08-26 21:03 UTC, meker12 requested changes

2019-08-26 21:03 UTC, meker12 commented on dist/.magento.env.yaml
> +# CONSUMERS_WAIT_MAX_MESSAGES - use this variable to configure consumers behavior.                                    #
I think it is better:  CONSUMERS_WAIT_FOR_MAX_MESSAGES

2019-08-26 21:03 UTC, meker12 commented on dist/.magento.env.yaml
> +#                               If this value is true, then a consumer waits for a message to process it, until       #
If this value is `true`, a consumer waits to process the number of messages (`max_messages`) from the message queue specified in the `CRONS_CONSUMERS_RUNNER` variable before closing the connection.  If you use workers to run consumers instead of using a cron job, set the `CONSUMERS_WAIT_FOR_MAX_MESSAGES` variable to `true`.

2019-08-26 21:03 UTC, meker12 commented on dist/.magento.env.yaml
> +#                               processes max-messages from a queue.                                                  #
```suggestion
```

2019-08-26 21:03 UTC, meker12 commented on dist/.magento.env.yaml
> +#                               If this value is false, then a consumer processes available  messages from a queue    #
If this value is `false`, consumers process available messages in the queue and close the TCP connection. Consumers do not wait for additional messages to enter the queue, even if the number of processed messages is less than the `max_messages` value.

2019-08-26 21:03 UTC, meker12 commented on dist/.magento.env.yaml
> +# CONSUMERS_WAIT_MAX_MESSAGES - use this variable to configure consumers behavior.                                    #
```suggestion
CONSUMERS_WAIT_FOR_MAX_MESSAGES - use this variable to configure how consumers process messages.    #
```

2019-08-27 14:17 UTC, shiftedreality approved these changes

2019-08-27 14:39 UTC, billygilbert approved these changes

2019-08-27 15:15 UTC, meker12 approved these changes
Provided an updated description which is easier to read and follows pattern of other env variable descriptions.

2019-08-27 15:15 UTC, meker12 commented on dist/.magento.env.yaml
> +#######################################################################################################################
Provided a gist with some updates to improve formatting and clarity. 
 https://gist.github.com/meker12/9c5d9e1f5d4ce1ecbe8daa6f2ef5c8e7
```
#######################################################################################################################
# CONSUMERS_WAIT_FOR_MAX_MESSAGES - use this variable to configure how consumers process messages from the message    #
#                                   queue                                                                             #
# Magento Version: 2.2.0 and later                                                                                    #
# Default value: false                                                                                                #
# Possible values:                                                                                                    #
#                  false — consumers process available messages in the queue, close the TCP connection, and terminate.#
#                          Consumers do not wait for additional messages to enter the queue, even if the number of    #
#                          processed messages is less than the `max_messages` value specified in the                  #
#                          CRON_CONSUMERS_RUNNER deploy variable.                                                     #
#                  true —  consumers continue to process messages from the message queue until reaching the maximum   #
#                          number of messages (`max_messages`) specified in the CRON_CONSUMERS_RUNNER deploy variable #
#                          before closing the TCP connection and terminating the consumer process. If the queue       #
#                          empties before reaching `max_messages` the consumer waits for more messages to arrive. If  #
#                          you use workers to run consumers instead of using a cron job, set this variable to true.   #
# Stages: deploy                                                                                                      #
# Example:                                                                                                            #
#          stage:                                                                                                     #
#            deploy:                                                                                                  #
#              CONSUMERS_WAIT_FOR_MAX_MESSAGES: true                                                                  #
#######################################################################################################################
```

2019-08-27 15:21 UTC, BaDos commented on dist/.magento.env.yaml
> +#######################################################################################################################
Thanks!
I will add this change to develop branch.
Currently, all builds are green and we need to test and merge this PR and then start regression.

2019-08-27 17:29 UTC, mveeramneni commented
QA Approved

2019-08-27 17:33 UTC, merged