MAGECLOUD-4116: Adding a strict_types sniffer for ece-tools.
magento/ece-tools pull request #610
Opened 2019-09-23 18:35 UTC by sikharam-adb

### Description

### Fixed Issues (if relevant)

1. magento/ece-tools#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-09-23 18:50 UTC, shiftedreality requested changes

2019-09-23 18:50 UTC, shiftedreality commented on tests/static/Sniffs/Directives/StrictTypesSniff.php
> +     * Description: Fixer to add the strict_types declaration.
Remove `Description: ` and add a new line after description body

2019-09-23 18:50 UTC, shiftedreality commented on tests/static/Sniffs/Directives/StrictTypesSniff.php
> +    private function scan(File $phpcsFile, array $tokens, int $position) : bool
The same as previous

2019-09-23 18:50 UTC, shiftedreality commented on tests/static/Sniffs/Directives/StrictTypesSniff.php
> + * Description: Sniffer to check if the strict_types declaration is included and add it if not.
Remove `Description: `

2019-09-24 16:05 UTC, bbatsche requested changes

2019-09-24 16:05 UTC, bbatsche commented on tests/static/Sniffs/Directives/StrictTypesSniff.php
> +namespace Magento\MagentoCloud\Test\Sniffs\Directives;
I feel like there's some irony in a sniff that doesn't sniff itself. Where's `declare(strict_types=1);` here?

2019-09-24 16:05 UTC, bbatsche commented on tests/static/Sniffs/Directives/StrictTypesSniff.php
> +    // Flag to keep track of whether the file has been fixed.
This should be formatted as a PHPDoc block. The comment can remain, but it also needs `@var` annotation.

2019-09-24 16:05 UTC, bbatsche commented on tests/static/Sniffs/Directives/StrictTypesSniff.php
> +     * @return array|mixed[]
I could be wrong, but I think `array` and `mixed[]` would be synonymous. You can keep it to just `array`

2019-09-24 16:05 UTC, bbatsche commented on tests/static/Sniffs/Directives/StrictTypesSniff.php
> +        // Get all tokens.
I like well commented code, however some of these are doing more of describing "what" and not really "why". I'm not suggesting you change any of them at this point but something to be aware of in the future.

2019-09-24 16:05 UTC, bbatsche commented on tests/static/Sniffs/Directives/StrictTypesSniff.php
> +            return false;
Always wrap `if` statement body with `{}`

2019-09-24 16:05 UTC, bbatsche commented on tests/static/Sniffs/Directives/StrictTypesSniff.php
> +    private function fix(File $phpcsFile, int $position)
If a method does not return anything, it should be type hinted with `: void` (This is a recent addition since dropping support for PHP 7.0)

2019-09-24 16:05 UTC, bbatsche commented on tests/static/Sniffs/Directives/StrictTypesSniff.php
> +            $this->scan($phpcsFile, $tokens, $phpcsFile->findPrevious([T_DECLARE], $position - 1));
Should there be a `return` statement here?

2019-09-24 19:11 UTC, bbatsche requested changes

2019-09-24 19:11 UTC, bbatsche commented on tests/static/Sniffs/Directives/StrictTypesSniff.php
> + * @package Magento\MagentoCloud\Test\Sniffs\Directives
Do not use `@package` annotation

2019-09-25 15:30 UTC, bbatsche commented on src/Filesystem/Driver/File.php
> +        $result = @file_put_contents($path, $content, $mode ?? 0);
I would have just modified the default value for `$mode` on line 383, but this is fine

2019-09-25 16:43 UTC, bbatsche approved these changes

2019-09-25 17:53 UTC, shiftedreality approved these changes

2019-09-25 17:54 UTC, merged