MAGECLOUD-4100: Copy the link to this issue  Introduce DI component
magento/ece-tools pull request #618
Opened 2019-10-03 13:42 UTC by oshmyheliuk

https://magento2.atlassian.net/browse/MAGECLOUD-4100

### Description

### Fixed Issues (if relevant)

1. magento/ece-tools#<issue_number>: Issue title
2. ...

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2019-10-03 14:37 UTC, oshmyheliuk commented on config/services/build/generate.xml
> +<?xml version="1.0" encoding="UTF-8" ?>
Files generate.xml and transfer.xml just examples of how ece-tools commands can be configured by Symfony DI.
But at the moment this has no sense as they are configured in scneario*.xml files.

2019-10-03 18:58 UTC, shiftedreality requested changes

2019-10-03 18:58 UTC, shiftedreality commented on src/App/Container.php
> +        $definition = new Definition();
This is defined in `services.xml`

2019-10-03 18:59 UTC, shiftedreality commented on config/services.xml
> +
Excessive empty line

2019-10-03 19:01 UTC, shiftedreality commented on src/App/Container.php
> +        $composerFactory = new \Composer\Factory();
Please use import from namespace

2019-10-03 19:12 UTC, oshmyheliuk commented on src/App/Container.php
> +        $composerFactory = new \Composer\Factory();
done

2019-10-03 19:12 UTC, oshmyheliuk commented on config/services.xml
> +
removed

2019-10-03 19:13 UTC, oshmyheliuk commented on src/App/Container.php
> +        $definition = new Definition();
Agree, removed

2019-10-03 19:58 UTC, shiftedreality commented
Travis CI static/unit tests

2019-10-07 14:11 UTC, shiftedreality approved these changes

2019-10-07 20:41 UTC, BaDos approved these changes

2019-10-08 14:51 UTC, oshmyheliuk commented
QA done in automated tests.

2019-10-08 14:53 UTC, merged