MAGECLOUD-4887: Implement wizard for split Db  'wizard:split-db-state'
magento/ece-tools pull request #685
Opened 2020-02-12 20:57 UTC by NadiyaS

https://magento2.atlassian.net/browse/MAGECLOUD-4887

### Description
Implement CLI command which provides info about ability to split DB and whether DB was already split or not.
### Manual testing scenarios
Run command `wizard:split-db-state` on next cloud environments:
**1.** On any env, which does not support split DB. 
  Result: 
```
DB is not split:
- DB cannot be split on this environment
```
**2.** On env which support split DB.
  Result: 
```
DB is not split:
- You may split DB using SPLIT_DB variable in .magento.env.yaml file
```
**3.** On env which support split DB. And quote type was already split
  Result: 
```
DB is already split with type(s): quote
```
**4.** On env which support split DB. And quote and sales types were already split
  Result: 
```
DB is already split with type(s): quote, sales
```

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2020-02-13 17:23 UTC, billygilbert submitted a review, later dismissed

2020-02-14 12:13 UTC, arhiopterecs requested changes

2020-02-14 12:13 UTC, arhiopterecs commented on src/Command/Wizard/SplitDbState.php
> +    const NAME = 'wizard:split-db-state';
Add a description

2020-02-14 12:13 UTC, arhiopterecs commented on src/Command/Wizard/SplitDbState.php
> +    private $outputFormatter;
Add a description

2020-02-14 12:13 UTC, arhiopterecs commented on src/Command/Wizard/SplitDbState.php
> +    private $configReader;
Add a description

2020-02-14 12:13 UTC, arhiopterecs commented on src/Command/Wizard/SplitDbState.php
> +     * SplitDb constructor.
Please, delete this line

2020-02-18 15:14 UTC, NadiyaS commented on src/Command/Wizard/SplitDbState.php
> +    const NAME = 'wizard:split-db-state';
done

2020-02-18 15:14 UTC, NadiyaS commented on src/Command/Wizard/SplitDbState.php
> +    private $outputFormatter;
done

2020-02-18 15:14 UTC, NadiyaS commented on src/Command/Wizard/SplitDbState.php
> +    private $configReader;
done

2020-02-18 15:14 UTC, NadiyaS commented on src/Command/Wizard/SplitDbState.php
> +     * SplitDb constructor.
done

2020-02-18 16:00 UTC, arhiopterecs approved these changes

2020-02-18 16:24 UTC, arhiopterecs approved these changes

2020-02-18 16:29 UTC, billygilbert approved these changes

2020-02-20 22:59 UTC, andriyShevtsov commented
QA approved

2020-02-21 16:10 UTC, merged