MAGECLOUD-1122:  Fixing cron:run on non-production environments.
magento/ece-tools pull request #72
Opened 2017-10-31 20:03 UTC by JacobBrownAustin

https://magento2.atlassian.net/browse/MAGECLOUD-1122
### Description
We need to check if we are currently in a non-production environment, and if we are, then modify the module-cron so that it works around the fact that our cron:run will only run once every five minutes.  To do this, this pull request checks the environment variables MAGENTO_CLOUD_PROJECT and HOME to see if it is a production environment.  If it isn't, then it sets the $config["system"]["default"]["cron"]["cron_interval"] = "5"; in env.php .
This variable is used later in a patch that has a separate pull request in ece-patches.
It would be better if we could determine the cron interval on the current environment directly, but I asked Platform.sh, and there is no way to currently do this, so MAGENTO_CLOUD_PROJECT and HOME were the best that I could do for now.

### Fixed Issues (if relevant)
1. Find a way to determine whether or not we are in a production environment.
2. Set a variable in env.php that is later used by a patch in magento-patches

### Zephyr Tests

1. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] Pull request was approved by architect
 - [ ] Pull request was approved by QA member
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2017-11-02 17:17 UTC, shiftedreality requested changes
We should eliminate patch and think about more elegant solution, maybe using `config:set --lock`.
@JacobBrownAustin please book a meeting to discuss this item.

2017-11-06 12:26 UTC, shiftedreality requested changes

2017-11-14 22:16 UTC, billygilbert requested changes

2017-11-15 16:00 UTC, michaelcasey316 approved these changes

2017-12-15 10:23 UTC, closed without merging