MCLOUD-6144: Adjust service validators prior to 2.4.0 version
magento/ece-tools pull request #737
Opened 2020-06-04 17:52 UTC by BaDos

### Description

Align ECE-Tools validators with Magento 2.4.0
Align EOL validators with 2.4.0
Check & update other Magento/service version validators (Redis EOL,etc). 

### Fixed Issues (if relevant)

https://jira.corp.magento.com/browse/MCLOUD-6144

### Manual testing scenarios

Try to install 2.4.0 on the Magento Cloud

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2020-06-05 15:19 UTC, YPyltiai requested changes

2020-06-05 15:19 UTC, YPyltiai commented on src/Service/Validator.php
> +            '>=2.4.0' => '10.4',
This looks wrong to me. 2.4.0 should support older versions too. Why do we say 2.4.0 is 10.4 only?

2020-06-05 15:19 UTC, YPyltiai commented on src/Service/Validator.php
> +            '>=2.4.0' => '^6.2',
Same comment here as on DB. New version was added but are we sure old were dropped?

2020-06-05 15:19 UTC, YPyltiai commented on src/Service/Validator.php
> +            '>=2.3.5' => '~6.8.0 || ~7.2.0 || ~7.5.0',
Same as other services. Were old ES services actually dropped?

2020-06-05 15:19 UTC, YPyltiai commented on src/Service/Validator.php
> +            '>=2.3.5' => '~3.8.0',
Same as other services. Were old RMQ services actually dropped?

2020-06-05 15:54 UTC, BaDos commented
@YPyltiai Yes, you are right.
I will recheck all supported services.

2020-06-10 10:57 UTC, BarnyShergold requested changes

2020-06-10 10:57 UTC, BarnyShergold commented on src/Service/Validator.php
> +            '>=2.4.0' => '~7.4.0 || ~7.5.0 || ~7.6.0',
2.4.0 still supports ElasticSearch 6.8.x

2020-06-10 14:15 UTC, BaDos commented on src/Service/Validator.php
> +            '>=2.4.0' => '~7.4.0 || ~7.5.0 || ~7.6.0',
Hi @BarnyShergold,

We currently cannot guarantee that 2.4.0 works correctly with ES 6.8, because Magento modules require `"elasticsearch/elasticsearch": "~7.6"`

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Elasticsearch/composer.json
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Elasticsearch6/composer.json
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Elasticsearch7/composer.json

https://github.com/elastic/elasticsearch-php/tree/master#version-matrix

2020-06-10 14:31 UTC, BarnyShergold commented on src/Service/Validator.php
> +            '>=2.4.0' => '~7.4.0 || ~7.5.0 || ~7.6.0',
Then perhaps we should update the documentation on 2.4 and say so? 
Also if those modules have ~7.6 for the ES module then surely your line above should read ->=2.4.0' => '7.6.0' ?

If ES 7.4.x or 7.5.x were installed then then ~7.6 will cause issues?

2020-06-10 14:34 UTC, YPyltiai commented on src/Service/Validator.php
> +            '>=2.4.0' => '~7.4.0 || ~7.5.0 || ~7.6.0',
@BarnyShergold not really, ES says that elasticsearch/elasticsearch PHP lib works with server 7.4+ . That's pretty much what the constraint says.

EDIT: since core 2.4.0 has PHP lib for elasticsearch/elasticsearch v7.6.x, it will support server 7.4+ in current state unless something changes.

2020-06-10 14:35 UTC, BaDos commented on src/Service/Validator.php
> +            '>=2.4.0' => '~7.4.0 || ~7.5.0 || ~7.6.0',
We will update the documentation. Product Owners are discussing it.

> If ES 7.4.x or 7.5.x were installed then ~7.6 will cause issues?

No, ES 7.4 should work fine with ~7.6 according to this https://github.com/elastic/elasticsearch-php/tree/master#version-matrix

2020-06-10 14:37 UTC, BarnyShergold commented on src/Service/Validator.php
> +            '>=2.4.0' => '~7.4.0 || ~7.5.0 || ~7.6.0',
Ah right so with ES module it will generally support lower versions of the server on the main branch? IE module 7.6 will support 7.x server? but not 6.x? Or you just have to check each time? But if you have doubled checked the versioning and are sure then that's okay - I was just pointing out how it seemed :D

2020-06-10 14:49 UTC, YPyltiai commented on src/Service/Validator.php
> +            '>=2.4.0' => '~7.4.0 || ~7.5.0 || ~7.6.0',
@BarnyShergold not exactly - ES has strict mapping here: https://github.com/elastic/elasticsearch-php/tree/master#version-matrix

7.6.x PHP lib will work with server 7.4+ (but won't work with 7.0-7.3)

2020-06-10 15:39 UTC, BarnyShergold submitted a review, later dismissed

2020-06-11 18:47 UTC, oshmyheliuk submitted a review, later dismissed

2020-06-12 14:07 UTC, shiftedreality submitted a review, later dismissed

2020-06-12 14:15 UTC, YPyltiai requested changes
@BaDos , please add ES 7.7.0 and confirm if RabbitMQ is up to date.

2020-06-12 14:15 UTC, YPyltiai commented on src/Service/Validator.php
> +            '>=2.3.5 <2.4.0' => '~1.7.0 || ~2.4.0 || ~5.2.0 || ~6.5.0 || ~6.8.0|| ~7.4.0 || ~7.5.0 || ~7.6.0',
@BaDos , please add ~7.7.0

2020-06-12 14:15 UTC, YPyltiai commented on src/Service/Validator.php
> +            '>=2.4.0' => '~7.4.0 || ~7.5.0 || ~7.6.0',
@BaDos , please add ~7.7.0

2020-06-12 14:15 UTC, YPyltiai commented on src/Service/Validator.php
>          ServiceInterface::NAME_RABBITMQ => [
Didn't we have changes in RabbitMQ? I thought 3.8.0 was added.

2020-06-12 15:58 UTC, YPyltiai submitted a review, later dismissed

2020-06-12 17:58 UTC, shiftedreality submitted a review, later dismissed

2020-06-15 21:01 UTC, shiftedreality approved these changes

2020-06-15 21:02 UTC, YPyltiai approved these changes

2020-06-15 21:16 UTC, andriyShevtsov commented
QA approved

2020-06-16 14:05 UTC, merged